In [1]:
from preprocessing import SentencesEmbeddingDataset
embedding_type = "glove"
batch_size = 32
NER_dataset = SentencesEmbeddingDataset(embedding_model_type=embedding_type)
train_loader, dev_loader = NER_dataset.get_data_loaders(batch_size=batch_size)

prepering glove...


In [2]:
from model3_comp import LSTM_NER_NN
from train_loop_model3 import train_and_plot_LSTM

In [3]:
from torch.optim import Adam
import torch.nn as nn

num_classes = 2
num_epochs = 20
embedding_dim = NER_dataset.VEC_DIM
lr = 0.001

hidden_dim = 64
# activation = nn.ReLU()
# activation = nn.Sigmoid()
activation = nn.Tanh()
num_layers = 1

model_save_path = (
    f"LSTM_model_stateDict_batchSize_{batch_size}_hidden_{hidden_dim}_lr_{lr}.pt"
)

LSTM_model = LSTM_NER_NN(
    embedding_dim=embedding_dim,
    num_classes=num_classes,
    hidden_dim=hidden_dim,
    model_save_path=model_save_path,
    activation=activation,
    num_layers=num_layers,
)

optimizer = Adam(params=LSTM_model.parameters(), lr=lr)
loss_func = nn.CrossEntropyLoss()

train_and_plot_LSTM(
    LSTM_model=LSTM_model,
    train_loader=train_loader,
    num_epochs=num_epochs,
    val_loader=dev_loader,
    optimizer=optimizer,
    loss_func=loss_func,
)

hidden_dim=64 | activation=Tanh() | num_layers=1
No GPU available, training on CPU.
Batch: 1/107 | Batch Loss: 0.698 | Train Accuracy: 0.469 | Train F1: 0.093
Batch: 101/107 | Batch Loss: 0.378 | Train Accuracy: 0.944 | Train F1: 0.009
Epoch: 1/20 | Train Avg Loss: 0.395 | Train Accuracy: 0.944 | Train F1: 0.008
[[5.9214e+04 3.5600e+02]
 [3.1450e+03 1.5000e+01]]
Val Accuracy: 0.905 | Val F1: nan


/Users/kerengruteke/projects/NLP_course/HW/HW2/utils.py:14: RuntimeWarning: invalid value encountered in double_scalars
  precision = Tp / (Tp + Fp)


Val Accuracy: 0.921 | Val F1: nan
[[14483.     0.]
 [ 1250.     0.]]
Batch: 1/107 | Batch Loss: 0.361 | Train Accuracy: 0.953 | Train F1: nan
Batch: 101/107 | Batch Loss: 0.350 | Train Accuracy: 0.949 | Train F1: nan
Epoch: 2/20 | Train Avg Loss: 0.364 | Train Accuracy: 0.950 | Train F1: nan
[[59570.     0.]
 [ 3160.     0.]]
Val Accuracy: 0.930 | Val F1: nan
Val Accuracy: 0.921 | Val F1: nan
[[14483.     0.]
 [ 1250.     0.]]
Batch: 1/107 | Batch Loss: 0.347 | Train Accuracy: 0.967 | Train F1: nan
Batch: 101/107 | Batch Loss: 0.367 | Train Accuracy: 0.950 | Train F1: nan
Epoch: 3/20 | Train Avg Loss: 0.364 | Train Accuracy: 0.950 | Train F1: nan
[[59570.     0.]
 [ 3160.     0.]]
Val Accuracy: 0.956 | Val F1: nan
Val Accuracy: 0.921 | Val F1: nan
[[14483.     0.]
 [ 1250.     0.]]
Batch: 1/107 | Batch Loss: 0.364 | Train Accuracy: 0.950 | Train F1: nan
Batch: 101/107 | Batch Loss: 0.347 | Train Accuracy: 0.949 | Train F1: nan
Epoch: 4/20 | Train Avg Loss: 0.364 | Train Accuracy: 0.950