# model 3

In [2]:
from abc import ABC
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm import tqdm, trange
from preprocessing import SentencesEmbeddingDataset, WordsEmbeddingDataset
from model2_nn import train_and_plot
from torch.nn.utils import rnn

In [3]:
ds = SentencesEmbeddingDataset()

preparing embedding...


In [20]:
train_dataloader, test_dataloader = ds.get_data_loaders(batch_size=64)

In [39]:
dev_dataloader = test_dataloader

In [12]:
loss = nn.CrossEntropyLoss(reduction='none')
y = torch.Tensor([[0.5, 0.5], [0.6, 0.4], [0.2, 0.8]])
y_hat = torch.Tensor([[0, 1], [1, 0], [1, 0]])
samples_losses = loss(y, y_hat)
samples_losses

tensor([0.6931, 0.5981, 1.0375])

In [15]:
ds2 = WordsEmbeddingDataset()

prepering glove...


In [18]:
X_train, y_train, X_dev, y_dev = ds2.get_datasets()

In [25]:
train_dataloader.dataset[0]

(tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.2040,  0.4534, -0.1684,  ...,  0.3332, -0.2900,  0.2560],
         [ 0.1157,  0.0151,  0.2125,  ...,  0.3562, -0.1772,  0.0070],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]),
 27)